title: Patrick J. Trevenen
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about me learning Git and Github.  I am new to the developer world but it does look interesting and yet there is much to learn.

# social links
twitter_username: patricktrevenen
github_username:  trevenenpj2

show_excerpts: true # set to false to remove excerpts on the homepage
